routing:
    index: 
        path: /
        methods: [GET]
        controller: index:index
    login:
        path: /login
        methods: [GET, POST]
        controller: index:login
    reg:
        path: /reg
        methods: [GET, POST]
        controller: index:registration
    reg_complete:
        path: /reg/complete
        methods: [POST]
        controller: index:registrationComplete
    reg_verified:
        path: /reg/{token}
        methods: [GET]
        controller: index:registrationVerified
    logout:
        path: /logout
        methods: [GET]
        controller: index:logout
        csrf: true